import { boolean, integer, pgTable, text, timestamp } from "drizzle-orm/pg-core"

export const user = pgTable("user", {
  id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull(),
})
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt"), updatedAt: timestamp("updatedAt") })

export const tasks = pgTable("tasks", { id: text("id").primaryKey(), userId: text("userId").notNull(), title: text("title").notNull(), description: text("description"), status: text("status").notNull().default("queued"), priority: text("priority").notNull().default("normal"), assignee: text("assignee"), progress: integer("progress").notNull().default(0), qaStatus: text("qaStatus").notNull().default("pending"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull() })
export const agents = pgTable("agents", { id: text("id").primaryKey(), userId: text("userId").notNull(), name: text("name").notNull(), role: text("role").notNull(), status: text("status").notNull().default("idle"), model: text("model").notNull(), description: text("description"), lastHeartbeatAt: timestamp("lastHeartbeatAt"), createdAt: timestamp("createdAt").notNull() })
export const reports = pgTable("reports", { id: text("id").primaryKey(), userId: text("userId").notNull(), title: text("title").notNull(), type: text("type").notNull(), status: text("status").notNull().default("ready"), summary: text("summary"), createdAt: timestamp("createdAt").notNull() })
export const alerts = pgTable("alerts", { id: text("id").primaryKey(), userId: text("userId").notNull(), severity: text("severity").notNull().default("info"), title: text("title").notNull(), message: text("message").notNull(), resolved: boolean("resolved").notNull().default(false), createdAt: timestamp("createdAt").notNull() })
