import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core"

export const user = pgTable("user", {
  id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull(),
})
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt"), updatedAt: timestamp("updatedAt") })

export const tasks = pgTable("tasks", { id: text("id").primaryKey(), userId: text("userId").notNull(), title: text("title").notNull(), description: text("description"), status: text("status").notNull().default("queued"), priority: text("priority").notNull().default("normal"), assignee: text("assignee"), progress: integer("progress").notNull().default(0), qaStatus: text("qaStatus").notNull().default("pending"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull() })
export const agents = pgTable("agents", { id: text("id").primaryKey(), userId: text("userId").notNull(), name: text("name").notNull(), role: text("role").notNull(), status: text("status").notNull().default("idle"), model: text("model").notNull(), description: text("description"), lastHeartbeatAt: timestamp("lastHeartbeatAt"), createdAt: timestamp("createdAt").notNull() })
export const reports = pgTable("reports", { id: text("id").primaryKey(), userId: text("userId").notNull(), title: text("title").notNull(), type: text("type").notNull(), status: text("status").notNull().default("ready"), summary: text("summary"), createdAt: timestamp("createdAt").notNull() })
export const alerts = pgTable("alerts", { id: text("id").primaryKey(), userId: text("userId").notNull(), severity: text("severity").notNull().default("info"), title: text("title").notNull(), message: text("message").notNull(), resolved: boolean("resolved").notNull().default(false), createdAt: timestamp("createdAt").notNull() })

/* ------------------------------------------------- pension signal pipeline */

export const pensionRuns = pgTable("pension_runs", { id: text("id").primaryKey(), userId: text("userId").notNull(), source: text("source").notNull().default("upload"), status: text("status").notNull().default("complete"), asOf: text("asOf").notNull(), leadsRead: integer("leadsRead").notNull().default(0), duplicates: integer("duplicates").notNull().default(0), actionable: integer("actionable").notNull().default(0), averageScore: integer("averageScore").notNull().default(0), manifest: jsonb("manifest"), error: text("error"), createdAt: timestamp("createdAt").notNull() })

export const pensionLeads = pgTable("pension_leads", { id: text("id").primaryKey(), userId: text("userId").notNull(), dedupeKey: text("dedupeKey").notNull(), externalId: text("externalId"), firstName: text("firstName"), lastName: text("lastName"), email: text("email"), phone: text("phone"), state: text("state"), employer: text("employer"), role: text("role"), birthDate: text("birthDate"), hireDate: text("hireDate"), serviceYears: text("serviceYears"), linkedinUrl: text("linkedinUrl"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull() }, (table) => [uniqueIndex("pension_leads_user_dedupe_idx").on(table.userId, table.dedupeKey)])

export const pensionSignals = pgTable("pension_signals", { id: text("id").primaryKey(), userId: text("userId").notNull(), leadId: text("leadId").notNull(), runId: text("runId").notNull(), systemId: text("systemId"), systemName: text("systemName"), tierId: text("tierId"), tierLabel: text("tierLabel"), age: text("age"), serviceYears: text("serviceYears"), points: text("points"), signal: text("signal").notNull(), signalLabel: text("signalLabel").notNull(), unreducedRule: text("unreducedRule"), yearsToUnreduced: text("yearsToUnreduced"), unreducedDate: text("unreducedDate"), earlyEligibleNow: boolean("earlyEligibleNow").notNull().default(false), earlyRule: text("earlyRule"), score: integer("score").notNull().default(0), scoreBreakdown: jsonb("scoreBreakdown"), emailStatus: text("emailStatus"), sequenceKey: text("sequenceKey"), cta: text("cta"), dataGaps: jsonb("dataGaps"), actionable: boolean("actionable").notNull().default(false), rejectReason: text("rejectReason"), crmStatus: text("crmStatus").notNull().default("pending"), asOf: text("asOf").notNull(), rulesAsOf: text("rulesAsOf"), createdAt: timestamp("createdAt").notNull() }, (table) => [index("pension_signals_user_score_idx").on(table.userId, table.score), index("pension_signals_run_idx").on(table.runId)])
